services:
  - type: web
    name: hmivar-webservice
    runtime: node
    rootDir: webservice
    buildCommand: npm --prefix webservice install
    startCommand: node webservice/src/index.js
    envVars:
      - key: NODE_VERSION
        value: 18
