services:
  - type: web
    name: hmivar-webservice
    runtime: node
    rootDir: webservice
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
